### PR TITLE
fix facetview browser nav & share link generation

### PR DESCRIPTION
**Pull request by msarahan**
Back and forward buttons now work properly.
Fix share link button to create useful link.
Insert space after set of all images for ads view.

### CODE REVIEW

**Comment by chrismattmann** [comment]
hey @msarahan I think this PR needs to be updated to master and then can be merged.

**Comment by msarahan** [comment]
@chrismattmann merged - thanks.

**Comment by chrismattmann** [comment]
thanks @msarahan if you haven't deployed this yet I'll take a crack this weekend.

**Comment by msarahan** [comment]
@chrismattmann this is deployed.  I had to clear my browser cache to make
the browser back/forward buttons work, though - just be aware of that
limitation.  Presumably some old javascript file is getting cached and
needs to be cleared to allow the new one to be used.

**Pull request merged**
